// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class renameidentityuserrolelogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameidentityuserrolelogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201810010614144_renameidentityuser-role-login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
